dataset: WGBS-se #GSE79277-WGBS-single

protocol: WGBS
alignment_mode: end-to-end 
remove_duplications: true
directional: true

clip: 0
clip_3p: 0


ignore: 0

qc0: true
qc1: true
mapping: true
coverage: true

