dataset: WGBS-pe #GSE79277-WGBS-paired

protocol: WGBS
alignment_mode: end-to-end 
remove_duplications: true
directional: true

clip1: 0
clip1_3p: 0
clip2: 0
clip2_3p: 0

ignore_r1: 0
ignore_r2: 2

qc0: true
qc1: true
mapping: true
coverage: true

